version: '3.8'

services:
  turtlebot3_start_signal_sim:
    image: fbe-dockerreg.rwu.de/doz-iki/staehle-vls/amr-tb3:latest
    container_name: turtlebot3_start_signal_sim
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=10
      - ROS_LOCALHOST_ONLY=0
      - TURTLEBOT3_MODEL=burger
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - GAZEBO_MODEL_PATH=/home/iki_workspace/25ss_rs-246849/stage_5/models
      - GAZEBO_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/gazebo-11/plugins
      - GAZEBO_RESOURCE_PATH=/usr/share/gazebo-11
      - DISPLAY=:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./25ss_rs-246849/stage_5:/home/iki_workspace/src/25ss_rs-246849/stage_5
    working_dir: /home/rs-246849/iki_workspace/src/25ss_rs-246849/stage_5
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               source /home/rs-246849/iki_workpsace/install/setup.bash &&
               export TURTLEBOT3_MODEL=burger &&
               ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py &&
               ros2 run autorace_real start_signal_real"
